version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: comment-app-postgres
    environment:
      POSTGRES_DB: comment_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comment-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./comment-app
      dockerfile: Dockerfile
    container_name: comment-app-backend
    ports:
      - "3600:3600"  # Using your existing backend port
    env_file:
      - ./comment-app/.env  # Using your existing backend .env
    environment:
      # Override database for Docker environment
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/comment_app
      - PORT=3600
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - comment-app-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./comment-frontend
      dockerfile: Dockerfile
    container_name: comment-app-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./comment-frontend/.env.local
    environment:
      # Override API URL for Docker environment  
      - NEXT_PUBLIC_API_BASE=http://backend:3600
    depends_on:
      - backend
    networks:
      - comment-app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  comment-app-network:
    driver: bridge 